---
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
  namespace: java-app
  labels:
    app.kubernetes.io/name: java-app
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: java-mysql-eks-platform
data:
  DB_SERVER: mysql-primary.database.svc.cluster.local
  DB_NAME: java_app_db
