---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: java-app
  labels:
    app.kubernetes.io/name: java-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: java-mysql-eks-platform
spec:
  type: LoadBalancer

  selector:
    app.kubernetes.io/name: java-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
